dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/res/layout/listview_row_footer.xml
=> Added listview footer

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/FieldAdapter.java
=> Order forms without sections

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/AutoCompleteRow.java
=> move autocomplete settext before setadapter to make autocomplete works

dhis2-android-app/src/main/java/org/dhis2/mobile/io/holders/DataElementOperand.java, dhis2-android-app/src/main/java/org/dhis2/mobile/io/models/Field.java, dhis2-android-app/src/main/java/org/dhis2/mobile/network/URLConstants.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/CompulsoryDataElementUIdsDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/ReportDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/AutoCompleteRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/BooleanRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/CheckBoxRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/DatePickerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/GenderRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/IntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/LongTextRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/NegativeIntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/NumberRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/PosIntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/PosOrZeroIntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/RowCosmetics.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/TextRow.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> Feature validate compulsory entries

dhis2-android-app/src/main/AndroidManifest.xml, dhis2-android-app/src/main/java/org/dhis2/mobile/WorkService.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/BaseActivity.java
=> Added push of offline datavalues before update

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/AutoCompleteRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/IntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/LongTextRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/NegativeIntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/NumberRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/PosIntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/PosOrZeroIntegerRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/TextRow.java
=> Bug scrolling problems when press keyboard next

.gitignore, buddybuild_postclone.sh, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/MenuActivity.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/fragments/AboutUsFragment.java, dhis2-android-app/src/main/res/layout/fragment_about_us.xml, dhis2-android-app/src/main/res/menu/menu_drawer.xml, dhis2-android-app/src/main/res/raw/description, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/colors.xml, dhis2-android-app/src/main/res/values/dimens.xml, dhis2-android-app/src/main/res/values/donottranslate.xml, dhis2-android-app/src/main/res/values/strings.xml, generate_last_commit.sh
=> Feature add about menu

generate_last_commit.sh
=> fix path in generate_last_commit.sh

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/MenuActivity.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> Added confirm dialog before logout

.gitignore
=>  fix path of lastcommit file in gitignore

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/res/layout/activity_data_entry.xml
=> Feature hide save button

dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml
=> change app title on French & Swedish. closes #36

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/FieldAdapter.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/NotSupportedRow.java, dhis2-android-app/src/main/res/layout/listview_row_not_supported.xml, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> Added not supported rows

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java
=> Added  single section name on actionbar title

buddybuild_postbuild.sh, buddybuild_postclone.sh, build.gradle, dhis2-android-app/build.gradle, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/fragments/MyProfileFragment.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/views/FontAutoCompleteTextView.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/views/FontButton.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/views/FontEditText.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/views/FontRadioButton.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/views/FontTextView.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/configuration.xml
=> Feature add code test coverage

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/AutoCompleteRow.java
=> Bug review view holders

dhis2-android-app/src/main/java/org/dhis2/mobile/io/models/Field.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> Feature confirm exit survey

dhis2-android-app/src/main/java/org/dhis2/mobile/io/models/Form.java, dhis2-android-app/src/main/java/org/dhis2/mobile/network/URLConstants.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/DataElementOperandParser.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/ReportDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> Feature all fields required message

dhis2-android-app/src/main/java/org/dhis2/mobile/WorkService.java, dhis2-android-app/src/main/java/org/dhis2/mobile/io/Constants.java, dhis2-android-app/src/main/java/org/dhis2/mobile/network/URLConstants.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/DataSetCategoryOptionParser.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/DataSetMetaData.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/FormMetadataProcessorStrategy.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/FormsDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/LoginProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/ReportDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/ServerInfoProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/LoginActivity.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/PrefUtils.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> Bug add 2 25 support to sections categorycombooptions

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/NotSupportedRow.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/RowTypes.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/TextRow.java
=> fix crash on invalid viewholder view

dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/DayIterator.java
=> fix day iterator to show the same data than the web

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java
=> Solved bug when saving with no connexion.

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/fragments/AggregateReportFragment.java
=>  restart view on restart loader to hide invalids views

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/fragments/AggregateReportFragment.java
=> Bug category option combo not changing

dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> correct back out without saving messages

dhis2-android-app/src/main/AndroidManifest.xml
=> remove allowBackup from manifest

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/FieldAdapter.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/LongTextRow.java, dhis2-android-app/src/main/res/layout/listview_row_long_text.xml
=> make long text multiline

dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/ExpiryDayValidatorFactory.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/WeeklyExpiryDayValidator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/WeeklySaturdayExpiryDayValidator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/WeeklySundayExpiryDayValidator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/WeeklyThursdayExpiryDayValidator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/WeeklyWednesdayExpiryDayValidator.java, dhis2-android-app/src/test/java/org/dhis2/mobile/utils/date/expiryday/WeeklySaturdayExpiryDayValidatorTest.java, dhis2-android-app/src/test/java/org/dhis2/mobile/utils/date/expiryday/WeeklySundayExpiryDayValidatorTest.java, dhis2-android-app/src/test/java/org/dhis2/mobile/utils/date/expiryday/WeeklyThursdayExpiryDayValidatorTest.java, dhis2-android-app/src/test/java/org/dhis2/mobile/utils/date/expiryday/WeeklyWednesdayExpiryDayValidatorTest.java
=> Bug expiry day weekly crash

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java
=> Bug crashing rotation data entry

dhis2-android-app/src/main/java/org/dhis2/mobile/WorkService.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/FormsDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/LoginProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/LoginActivity.java
=> create first pull after login in the login activity progressbar

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/DataEntryActivity.java, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> show toast with read only reason

dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekIterator.java
=> Bug weekly iterator different periods

dhis2-android-app/build.gradle, dhis2-android-app/src/main/res/values-fr/strings.xml, dhis2-android-app/src/main/res/values-sv/strings.xml, dhis2-android-app/src/main/res/values/strings.xml
=> change package id to allow buddybuild and google play versions coexist

dhis2-android-app/build.gradle, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/filters/QuarterlyPeriodFilter.java
=> Solved crash when selecting Quaterly period in EPI stock

dhis2-android-app/src/main/java/org/dhis2/mobile/processors/DataSetApprovals.java
=> Added state APPROVED_ABOVE for check approval dataset.

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/adapters/dataEntry/rows/AutoCompleteRow.java
=> fixed save and recovery optionset from fields

dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/DateConstants.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/DateIteratorFactory.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/PeriodFilterFactory.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/BiWeeklyExpiryDayValidator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/expiryday/ExpiryDayValidatorFactory.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/filters/BiWeeklyPeriodFilter.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/BiWeekIterator.java, dhis2-android-app/src/test/java/org/dhis2/mobile/utils/date/expiryday/BiWeeklyExpiryDateValidatorTest.java, dhis2-android-app/src/test/java/periodFilters/BiWeeklyPeriodTest.java
Closes #144 
Tested in android-dev
=> Feature add biweekly period

build.gradle, dhis2-android-app/build.gradle, dhis2-android-app/src/main/AndroidManifest.xml, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/LauncherActivity.java
=> Feature add crashlitycs

dhis2-android-app/src/main/java/org/dhis2/mobile/ui/activities/MenuActivity.java
Close #151 
To see a dataset with values select:
-OrgUnit: ngelehun CHC 
-Dataset: emergency response
=> Bug crash open data entry

dhis2-android-app/src/main/java/org/dhis2/mobile/io/models/FormOptions.java, dhis2-android-app/src/main/java/org/dhis2/mobile/network/URLConstants.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/DataSetMetaData.java, dhis2-android-app/src/main/java/org/dhis2/mobile/processors/FormsDownloadProcessor.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/fragments/AggregateReportFragment.java, dhis2-android-app/src/main/java/org/dhis2/mobile/ui/fragments/PeriodPicker.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/CustomDateIteratorClass.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/DateIteratorFactory.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/BiMonthIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/BiWeekIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/DayIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/FinAprilYearIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/FinJulyYearIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/FinOctYearIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/MonthIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/QuarterYearIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/SixMonthAprilIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/SixMonthIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekSaturdayIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekSundayIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekThursdayIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekWednesdayIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/YearIterator.java
=> Feature limit periods data imput periods

dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/FinAprilYearIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/FinJulyYearIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/FinOctYearIterator.java
=> Bug bug with finalncial iterators

dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/BiWeekIterator.java, dhis2-android-app/src/main/java/org/dhis2/mobile/utils/date/iterators/WeekIterator.java
=> fix crash creating max date on week iterator
